### ISSUE TITLE
Rebuild the docker image

### ISSUE THREAD

**Issue by orowith2os** [rbo/silverblue-v4l2loopback#4]
It was last updated [9 months ago](https://quay.io/repository/rbo/silverblue-v4l2loopback/manifest/sha256:4997db2de6a76396e70077eb85cc7134b4fe043ec316139d405fabbbb2f13a2f?tab=vulnerabilities). It seems due for an update, doesn't it?

**Comment by rbo** [comment]
Please build on your own. I'm currently not using the module anymore.  Sorry
